### ISSUE TITLE
I can Start Discord bot[BUG]

### ISSUE THREAD

**Issue by WaynexGamer31** [Commandserver/FiveM-Dashboard-Bot#2]

**Comment by Poziv** [comment]
I'm experiencing the same issue I can't start the bot. Line 378 "client = Client" is the problem, however when I change it to "client = discord.Client" the bot starts up but doesn't display message.
Image: (https://user-images.githubusercontent.com/121404708/209738704-d009f924-85b7-44ae-85ea-ecc22793b390.png)

**Comment by Commandserver** [comment]
I need more details. e.g. errors, console output

**Comment by LunarLoom24** [comment]
Traceback (most recent call last):
  File "D:\Vamos.lv-Roleplay\Serveris0Backup-VPS(23.01.23)\statusbots2023-2\bot.py", line 378, in <module>
    client = Client(
             ^^^^^^^
  File "D:\Vamos.lv-Roleplay\Serveris0Backup-VPS(23.01.23)\statusbots2023-2\bot.py", line 107, in __init__
    self.loop.create_task(self.update_status_loop())
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\client.py", line 108, in __getattr__
    raise AttributeError(msg)
AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook

**Comment by LunarLoom24** [comment]
Any help I have same isuse bot can't be started

**Comment by Commandserver** [comment]
Ill take a look at it

**Comment by Commandserver** [comment]
You're using python 3.1
Try it with python 3.8 or 3.9

**Comment by LunarLoom24** [comment]
i can try use python 3.11.2. Are it will work?

**Comment by Commandserver** [comment]
No. Use python 3.8 or 3.9

**Comment by LunarLoom24** [comment]
2023-04-24 02:35:10,154:INFO:Started with python version 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
2023-04-24 02:35:10,155:WARNING:PyNaCl is not installed, voice will NOT be supported

**Comment by LunarLoom24** [comment]
Traceback (most recent call last):
  File "D:\Fracture Roleplay\testa\FiveM-Dashboard-Bot\bot.py", line 378, in <module>
    client = Client(
             ^^^^^^^
  File "D:\Fracture Roleplay\testa\FiveM-Dashboard-Bot\bot.py", line 107, in __init__
    self.loop.create_task(self.update_status_loop())
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\client.py", line 108, in __getattr__
    raise AttributeError(msg)
AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook

**Comment by Commandserver** [comment]
Firstly: use a newer version of python; see the requirements in the README.md

Secondly: have you installed the version `1.7.3` of discord.py?
